# @ConfigurationProperties(prefix="person")
person:
  name: qinjiang
  age: 3
  happy: false
  birth: 2022/02/1
  maps: {k1: v1, k2: v2}
  lists:
    - code
    - music
    - girl
  dog:
    name: 旺财
    age: 3


spring:
  activemq:
    non-blocking-redelivery: false

#  mvc:
#    static-path-pattern: /hello/